version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coco #password
      MYSQL_DATABASE: woof #woof_development
      MYSQL_USER: root
      MYSQL_PASSWORD: coco #password
    ports:
      - "3307:3306" # Change this if you want to change the port mapping OUTSIDE:INSIDE
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/woof"
    ports:
      - "3000:3000"
    depends_on:
      - db
#    links:
#      - db
    environment:
      DB_USER: root
      DB_NAME: woof_development
      DB_PASSWORD: coco #password
      DB_HOST: db
      # If you use capybarra, you need to install Qt. https://www.youtube.com/watch?v=dF6VQOZPZBM